apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - image: europe-west3-docker.pkg.dev/fair-syntax-457919-b9/auth/production
        name: auth
        imagePullPolicy: Always
        env:
          - name: PORT
            value: '3002'
          - name: AUTH_GRPC_URL
            value: '0.0.0.0:3003'
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: connectionString
          - name: JWT_PRIVATE_KEY_BASE64
            valueFrom:
              secretKeyRef:
                name: jwt
                key: privateKey
          - name: JWT_PUBLIC_KEY_BASE64
            valueFrom:
              secretKeyRef:
                name: jwt
                key: publicKey
          - name: LOGSFF_APP_ID
            valueFrom:
              secretKeyRef:
                name: logsff
                key: appId
          - name: LOGSFF_TOKEN
            valueFrom:
              secretKeyRef:
                name: logsff
                key: token
          - name: LOGSFF_URL
            valueFrom:
              secretKeyRef:
                name: logsff
                key: url
        ports:
          - containerPort: 3002
          - containerPort: 3003