apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth
  name: auth-grpc
spec:
  ports:
  - name: "grpc"
    port: 3003
    protocol: TCP
    targetPort: 3003
  selector:
    app: auth
  type: ClusterIP