steps:
  # Reservations
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'europe-west3-docker.pkg.dev/fair-syntax-457919-b9/reservations/production',
      '-f',
      'apps/reservations/Dockerfile',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'europe-west3-docker.pkg.dev/fair-syntax-457919-b9/reservations/production'
    ]
  # Auth
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'europe-west3-docker.pkg.dev/fair-syntax-457919-b9/auth/production',
      '-f',
      'apps/auth/Dockerfile',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'europe-west3-docker.pkg.dev/fair-syntax-457919-b9/auth/production'
    ]
  # Payments
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'europe-west3-docker.pkg.dev/fair-syntax-457919-b9/payments/production',
      '-f',
      'apps/payments/Dockerfile',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'europe-west3-docker.pkg.dev/fair-syntax-457919-b9/payments/production'
    ]
  # Notifications
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'europe-west3-docker.pkg.dev/fair-syntax-457919-b9/notifications/production',
      '-f',
      'apps/notifications/Dockerfile',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'europe-west3-docker.pkg.dev/fair-syntax-457919-b9/notifications/production'
    ]

options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: 'projects/fair-syntax-457919-b9/serviceAccounts/cloudbuild-sa@fair-syntax-457919-b9.iam.gserviceaccount.com'