services:
  e2e:
    build: 
      dockerfile: ./Dockerfile
    volumes: 
      - ./specs:/usr/src/app/specs
    depends_on:
      - reservations
      - auth
      - payments
      - notifications
  reservations:
    depends_on:
      - mysql
    image: europe-west3-docker.pkg.dev/fair-syntax-457919-b9/reservations/production
    ports: 
        - '3000:3000'
    env_file:
        - ../apps/reservations/.env.docker
  auth:
    depends_on:
      - mysql
    image: europe-west3-docker.pkg.dev/fair-syntax-457919-b9/auth/production
    ports: 
        - '3001:3001'
    env_file:
        - ../apps/auth/.env.docker
  payments:
    image: europe-west3-docker.pkg.dev/fair-syntax-457919-b9/payments/production
    ports: 
        - '3003:3003'
    env_file:
      - ../apps/payments/.env.docker
  notifications:
    image: europe-west3-docker.pkg.dev/fair-syntax-457919-b9/notifications/production
    ports: 
        - '3004:3004'
    env_file:
        - ../apps/notifications/.env.docker
  mysql:
      image: mysql
      env_file: 
        - ../.env
      ports:
        - '3306:3306'