apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
      - image: europe-west3-docker.pkg.dev/fair-syntax-457919-b9/notifications/production
        name: notifications
        env:
          - name: NOTIFICATIONS_PORT
            value: '3000'
          - name: RESEND_FROM
            value: 'aird@ebartur.com'
          - name: RESEND_API_KEY
            valueFrom:
              secretKeyRef:
                name: resend
                key: apiKey
          - name: LOGSFF_APP_ID
            valueFrom: 
              secretKeyRef:
                name: logsff
                key: appId
          - name: LOGSFF_TOKEN
            valueFrom:
              secretKeyRef:
                name: logsff
                key: token
          - name: LOGSFF_URL
            valueFrom:
              secretKeyRef:
                name: logsff
                key: url
        ports:
          - containerPort: 3000