apiVersion: v1
kind: Service
metadata:
  labels:
    app: notifications
  name: notifications-grpc
spec:
  ports:
  - name: "grpc"
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: notifications
  type: ClusterIP
