apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payments
  name: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - image: europe-west3-docker.pkg.dev/fair-syntax-457919-b9/payments/production
        name: payments
        imagePullPolicy: Always
        env:
          - name: PAYMENT_GRPC_URL
            value: '0.0.0.0:3001'
          - name: NOTIFICATION_GRPC_URL
            value: 'notifications-grpc:3000'
          - name: STRIPE_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: stripe
                key: apiKey
          - name: LOGSFF_APP_ID
            valueFrom:
              secretKeyRef:
                name: logsff
                key: appId
          - name: LOGSFF_TOKEN
            valueFrom:
              secretKeyRef:
                name: logsff
                key: token
          - name: LOGSFF_URL
            valueFrom:
              secretKeyRef:
                name: logsff
                key: url
        ports:
          - containerPort: 3001