apiVersion: v1
kind: Service
metadata:
  labels:
    app: payments
  name: payments-grpc
spec:
  ports:
  - name: "grpc"
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: payments
  type: ClusterIP
